export enum AuditAction {
  REGISTER = 'REGISTER',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',

  VERIFY_EMAIL = 'VERIFY_EMAIL',

  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',

  CHANGE_PASSWORD = 'CHANGE_PASSWORD',

  UPDATE_PROFILE = 'UPDATE_PROFILE',

  DELETE_ACCOUNT = 'DELETE_ACCOUNT',

  SUSPEND_USER = 'SUSPEND_USER',
  ACTIVATE_USER = 'ACTIVATE_USER',

  CHANGE_ROLE = 'CHANGE_ROLE',
}
